#! /bin/bash
# build-distribution
# Part of ComixCursors, a desktop cursor theme.
#
# Copyright © 2010 Ben Finney <ben+gnome@benfinney.id.au>
# Copyright © 2006–2010 Jens Luetkens <j.luetkens@hamburg.de>
#
# This work is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This work is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this work. If not, see <http://www.gnu.org/licenses/>.

# This script creates all four packages of ComixCursors for distribution
# from the sources. Run it as root from inside the sources directory.

set -o errexit

VERSION="0.6.1"
export VERSION

themename_root="ComixCursors"
variants=("LH-Opaque" "LH" "Opaque" "")
distdir="${PWD}/dist"

#
# start
#

printf "Packaging %s %s...\n" "$themename_root" $VERSION

workdir="$(mktemp -t -d)"

#
# source package
#
printf "Creating source package...\n"

make clean
srcname="${themename_root}-sources-${VERSION}"
srcdir="${workdir}/${srcname}"
mkdir --parents "${srcdir}"
cp -a . "$srcdir"/.

mkdir --parents "$distdir"
rm -rf "$distdir"/*

tarfile="${distdir}/${srcname}.tar.bz2"
if [ -f "$tarfile" ] ; then rm "$tarfile"; fi
tar -cjf "$tarfile" --exclude-vcs --directory "$workdir" "$srcname"/

#
# Now build the cursors for packaging.
#

printf "Installing cursor files...\n"

# Make a temporary directory for installing icons into.
ICONSDIR="${workdir}/icons"
export ICONSDIR
mkdir --parents "${ICONSDIR}"

./install-all.sh

for variant in "${variants[@]}" ; do
    #
    # cursors packages
    #
    if [ -n "$variant" ] ; then
        packagename="${themename_root}-${variant}"
    else
        packagename="${themename_root}"
    fi

    printf "Creating cursors package %s...\n" "$packagename"

    # now it's important that the $variants get processed in an
    # "reverse" order, so only directories matching package name get
    # moved and packaged.

    packagedir="${workdir}/${packagename}"
    mkdir --parents "$packagedir"
    mv "${ICONSDIR}/${packagename}"* "$packagedir"/.

    tarfile="${distdir}/${packagename}-${VERSION}.tar.bz2"
    if [ -f "$tarfile" ] ; then rm "$tarfile" ; fi
    tar -cjf "$tarfile" --directory "$packagedir" "$packagedir"/*

    #
    # RPM packages
    #
    rpmdir="/usr/src/packages"
    if [ -d "$rpmdir" ] ; then
        printf "Creating RPM package...\n"
        specfile="${rpmdir}/SPECS/${packagename}.spec"
        rpmsourcesdir="${rpmdir}/SOURCES"
        make "${themename_root}.spec"
        cp "${themename_root}.spec" "$specfile" 
        cp "$tarfile" "${rpmsourcesdir}"/.
        (
            cd "$rpmsourcesdir"
            rpmbuild -bb "$specfile"
        )
        mv "${rpmdir}/RPMS/noarch/${packagename}"* "$distdir"/.
    else
        printf "Directory $rpmdir not found, skipping RPM packaging.\n"
    fi

done

printf "Cleaning up temporary working area...\n"
rm -r "$workdir"

printf "Done.\n"
