#! /bin/sh
# build-distribution
# Part of ComixCursors, a desktop cursor theme.
#
# Copyright © 2010 Ben Finney <ben+gnome@benfinney.id.au>
# Copyright © 2006–2010 Jens Luetkens <j.luetkens@hamburg.de>
#
# This work is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This work is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this work. If not, see <http://www.gnu.org/licenses/>.

# This script creates all four packages of ComixCursors for distribution
# from the sources. Run it as root from inside the sources directory.

VERSION="0.6.1"
PKGS="ComixCursors-LH-opaque ComixCursors-LH ComixCursors-opaque ComixCursors"
BASEDIR="$PWD"
DISTDIR="${PWD}/dist"

# Set the ICONSDIR destination to a default (if not already set).
ICONSDIR="${ICONSDIR:-~/.icons}"
export ICONSDIR

mkdir --parents "$DISTDIR"
rm -rf "$DISTDIR"/*

for PKG in $PKGS ; do

    cd "$BASEDIR"
    SUBDIR="$PKG-sources-$VERSION"

    if [ ! -d "$SUBDIR" ] ; then
        printf "Error: directory $SUBDIR not found, exiting.\n" >&2
        exit 1
    fi

    printf "Packaging $PKG $VERSION...\n"

    #
    # source packages
    #
    printf "Creating source package...\n"

    cd "$SUBDIR"
    make clean
    cd "$BASEDIR"
    TARFILE="$SUBDIR.tar.bz2"
    if [ -f "$TARFILE" ] ; then rm "$TARFILE" ; fi
    tar -cjf "$TARFILE" "$SUBDIR"
    mv "$TARFILE" "$DISTDIR"

    printf "Installing cursor files...\n"

    cd "$SUBDIR"
    ./install-all.sh
    cp cursorlinks "${ICONSDIR}"/

    #
    # cursors packages
    #
    printf "Creating cursors package...\n"

    # now it's important that the $PKGS get processed in an "reverse" order,
    # so only directories matching package name get packed.

    cd "${ICONSDIR}"/
    TARFILE="$PKG-$VERSION.tar.bz2"
    if [ -f "$TARFILE" ] ; then rm "$TARFILE" ; fi
    tar -cjhf "$TARFILE" "$PKG"* cursorlinks
    mv "$TARFILE" "$DISTDIR"
    rm -rf "$PKG"*

    #
    # RPM packages
    #
    PKGDIR="/usr/src/packages"
    if [ -d "$PKGDIR" ] ; then
        printf "Creating RPM package...\n"
        cd "$BASEDIR"
        cp "$SUBDIR/$PKG.spec" "$PKGDIR/SPECS/$PKG.spec"
        cp "$DISTDIR/$PKG-$VERSION.tar.bz2" "$PKGDIR/SOURCES/$PKG-$VERSION.tar.bz2"
        cd "$PKGDIR/SOURCES"/
        rpmbuild -bb "$PKGDIR/SPECS/$PKG.spec"
        mv "$PKGDIR/RPMS/noarch/$PKG"* "$DISTDIR"
    else
        printf "Directory $PKGDIR not found, skipping RPM packaging.\n"
    fi

done
