#! /bin/bash
# diffanimations
# Part of ComixCursors, a desktop cursor theme.
#
# Copyright © 2010 Ben Finney <ben+gnome@benfinney.id.au>
# Copyright © 2006–2010 Jens Luetkens <j.luetkens@hamburg.de>
#
# This work is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This work is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this work.
# If not, see <http://www.gnu.org/licenses/>.

# Create the patch files for animated cursor images.

# cd animations

function make_cumulative_patch {
    # Make a patch file between each consecutive part of a cursor sequence.
    cursorname="$1"
    parts_count=$2

    patch_file="${cursorname}.diff"

    (for this_part in $(seq $parts_count -1 2) ; do
        prev_part=$(($this_part - 1))
        this_file="${cursorname}${this_part}.svg"
        prev_file="${cursorname}${prev_part}.svg"
        diff "${prev_file}" "${this_file}"
    done) > "${patch_file}"
}

make_cumulative_patch "wait" 36
make_cumulative_patch "progress" 24
